site_name: Quantum Algorithm Documentation
site_description: 基于稀疏态模拟器PySparQ的量子算法库
site_author: USTC-IAI量子计算团队
site_url: https://qalgo.readthedocs.io/

nav:
  - Home: index.md
  - Getting Started: start.md
  # - Usage: usage.md
  - Algorithms:
      - Quantum Discrete Adiabatic: algorithms/qda.md
  # - PySparQ Reference: pysparq.md
  - Development: development.md
  - API Reference: 
      - Quantum Discrete Adiabatic: api/qda.md
      - Utils: api/utils.md
  - About: about.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings
    # default_handler: python
    # handlers:
    #   python:
    #     options:


markdown_extensions:
  - toc:
      permalink: true
  - attr_list